language: node_js

node_js:
  - 8.12.0

cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master